### ISSUE TITLE
oVirt / RHV 4.2

### ISSUE THREAD

**Issue by righteousjester** [oVirt/ovirt-openshift-extensions#39]
I am attempting to get this working on Openshift 3.9 and RHV 4.2.
Will this work on these versions?

openshift version
openshift v3.9.30
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16

RHV Version 4.2.3.8-0.1.el7

I see the following in the logs when I try to provision a PVC

I0629 08:07:48.717468       1 provision.go:73] About to provision a disk name: pvc-703fe2bb-7966-11e8-9a68-001a4a1601ae domain: XXXXXXXXX size: 107374182400 format:  
{"name":"pvc-703fe2bb-7966-11e8-9a68-001a4a1601ae","actual_size":0,"provisioned_size":107374182400,"format":"raw","storage_domains":{"storage_domain":[{"name":"XXXXXXXXX"}]}}
E0629 08:07:48.839967       1 controller.go:801] Failed to provision volume for claim "default/registry" with StorageClass "ovirt": 400 Bad Request
E0629 08:07:48.840074       1 goroutinemap.go:165] Operation for "provision-default/registry[703fe2bb-7966-11e8-9a68-001a4a1601ae]" failed. No retries permitted until 2018-06-29 08:09:50.840054564 +0000 UTC m=+1172.319234664 (durationBeforeRetry 2m2s). Error: 400 Bad Request

Thanks for creating this project :)

**Comment by rgolangh** [comment]
Yes the openshift and RHV versions are fine. I think the the error is about not having a storage class 'ovirt' .  what does `oc get sc` say?  how did you install it?

**Comment by righteousjester** [comment]
Here you go

```
oc get sc
NAME              PROVISIONER      AGE
ovirt (default)   external/ovirt   5d
```

```
oc export sc
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: null
    name: ovirt
  parameters:
    fsType: xfs
    iopsPerGB: "10"
    ovirtStorageDomain: XXXXXXXXX
    type: io1
  provisioner: external/ovirt
  reclaimPolicy: Delete
kind: List
metadata: {}
```

**Comment by rgolangh** [comment]
double check the ovirtStorageDomain is what you have in ovirt.  More of the provisioner log may help. I'll try to reproduce that with a non existing domain. What do you see in ovirt engine.log?

**Comment by righteousjester** [comment]
Here is the snippet.

```
2018-07-02 14:28:59,939+02 INFO  [org.ovirt.engine.core.bll.aaa.CreateUserSessionCommand] (default task-110) [46b34d1a] Running command: CreateUserSessionCommand internal: false.
2018-07-02 14:28:59,951+02 INFO  [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (default task-110) [46b34d1a] EVENT_ID: USER_VDC_LOGIN(30), User ovirt-openshift-extensions@internal-authz connecting from '10.227.169.140' using session 'WdJjGttFoi/qKWSuOS+ueFQiaAUB48UBJIPT8jwaEqyMOliZzRcamrQvf7c1mbkPcs8rWMC3HZJRtGH9Fpt6gw==' logged in.
2018-07-02 14:29:00,036+02 WARN  [org.ovirt.engine.core.bll.storage.disk.AddDiskCommand] (default task-110) [22a3d504-27d5-4096-a8c3-14ed6528a0b1] Validation of action 'AddDisk' failed for user ovirt-openshift-extensions@internal-authz. Reasons: VAR__ACTION__ADD,VAR__TYPE__DISK,ACTION_TYPE_FAILED_DISK_CONFIGURATION_NOT_SUPPORTED,$volumeFormat RAW,$volumeType Sparse
2018-07-02 14:29:00,042+02 ERROR [org.ovirt.engine.api.restapi.resource.AbstractBackendResource] (default task-110) [] Operation Failed: [Cannot add Virtual Disk. Disk configuration (RAW Sparse) is incompatible with the storage domain type.]
2018-07-02 14:29:01,772+02 WARN  [org.ovirt.engine.core.bll.storage.disk.AddDiskCommand] (default task-6) [6c24a2e5-e051-45aa-9923-d3edc6f38284] Validation of action 'AddDisk' failed for user ovirt-openshift-extensions@internal-authz. Reasons: VAR__ACTION__ADD,VAR__TYPE__DISK,ACTION_TYPE_FAILED_DISK_CONFIGURATION_NOT_SUPPORTED,$volumeFormat RAW,$volumeType Sparse
2018-07-02 14:29:01,778+02 ERROR [org.ovirt.engine.api.restapi.resource.AbstractBackendResource] (default task-6) [] Operation Failed: [Cannot add Virtual Disk. Disk configuration (RAW Sparse) is incompatible with the storage domain type.]
```
Looks like it doesn't support RAW.

**Comment by rgolangh** [comment]
It supports raw but I think your storage domain is iscsi, which led an attempt crate a spare disk using a raw device

**Comment by righteousjester** [comment]
Storage domain is Fiber Channel.
Format: V4

**Comment by rgolangh** [comment]
Ok the same case as iscsi then - block storage domains (FC or iSCCI) don't support a sparse disk with raw - which is the default that I set in the code. I'll remove it, so the defaults will be set by ovirt-engine api

**Comment by righteousjester** [comment]
I pulled down all the latest docker images you push in a few hours ago and rebuilt the project from scratch and this time I am getting a new error

```
2018-07-03 19:11:36,540+02 INFO  [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (default task-121) [40e689e8] EVENT_ID: USER_VDC_LOGIN(30), User ovirt-openshift-extensions@internal-authz connecting from '10.227.169.140' using session 'x/tTGV/IJLQDtBRx075OjqtK/NCTmL+Q2j6jkn7qyVntB/mzFBg7ZRlXQDeIB10nRUExmWewm9UCyMSBZrUn8g==' logged in.
2018-07-03 19:11:36,549+02 ERROR [org.ovirt.engine.api.restapi.resource.validation.JsonExceptionMapper] (default task-121) [] JSON exception while processing "POST" request for path "/disks"
2018-07-03 19:11:36,549+02 ERROR [org.ovirt.engine.api.restapi.resource.validation.JsonExceptionMapper] (default task-121) [] Exception: org.codehaus.jackson.map.JsonMappingException: Unable to unmarshal (to type [simple type, class java.lang.String]): The string '' isn't a valid value for the 'DiskFormat' enumerated type. Valid values are: 'cow', 'raw'. (through reference chain: org.ovirt.engine.api.model.Disk["format"])
	at org.codehaus.jackson.xc.XmlAdapterJsonDeserializer.deserialize(XmlAdapterJsonDeserializer.java:63)
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$FieldProperty.deserializeAndSet(SettableBeanProperty.java:579)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2704)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1315)
	at org.codehaus.jackson.jaxrs.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:419)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.interception.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:61) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.security.doseta.DigitalVerificationInterceptor.aroundReadFrom(DigitalVerificationInterceptor.java:36) [resteasy-crypto.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:59) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:151) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:92) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:115) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:138) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:101) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs.jar:3.0.25.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jboss-servlet-api_3.1_spec.jar:1.0.0.Final-redhat-1]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:81) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:274) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:209) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:221) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImplSetup(RequestDispatcherImpl.java:147) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:111) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.api.restapi.invocation.VersionFilter.doFilter(VersionFilter.java:180) [restapi-jaxrs.jar:]
	at org.ovirt.engine.api.restapi.invocation.VersionFilter.doFilter(VersionFilter.java:98) [restapi-jaxrs.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.api.restapi.invocation.CurrentFilter.doFilter(CurrentFilter.java:117) [restapi-jaxrs.jar:]
	at org.ovirt.engine.api.restapi.invocation.CurrentFilter.doFilter(CurrentFilter.java:72) [restapi-jaxrs.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.core.aaa.filters.RestApiSessionMgmtFilter.doFilter(RestApiSessionMgmtFilter.java:78) [aaa.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.core.aaa.filters.EnforceAuthFilter.doFilter(EnforceAuthFilter.java:42) [aaa.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.core.aaa.filters.SsoRestApiNegotiationFilter.doFilter(SsoRestApiNegotiationFilter.java:84) [aaa.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.core.aaa.filters.SsoRestApiAuthFilter.doFilter(SsoRestApiAuthFilter.java:47) [aaa.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.core.aaa.filters.SessionValidationFilter.doFilter(SessionValidationFilter.java:59) [aaa.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.core.aaa.filters.RestApiSessionValidationFilter.doFilter(RestApiSessionValidationFilter.java:35) [aaa.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.api.restapi.security.CSRFProtectionFilter.doFilter(CSRFProtectionFilter.java:111) [restapi-jaxrs.jar:]
	at org.ovirt.engine.api.restapi.security.CSRFProtectionFilter.doFilter(CSRFProtectionFilter.java:102) [restapi-jaxrs.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.ovirt.engine.core.utils.servlet.CORSSupportFilter.doFilter(CORSSupportFilter.java:284) [utils.jar:]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet.jar:1.4.18.SP2-redhat-1]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:330) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812) [undertow-core.jar:1.4.18.SP2-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_171]
Caused by: org.ovirt.engine.api.utils.InvalidEnumValueException: The string '' isn't a valid value for the 'DiskFormat' enumerated type. Valid values are: 'cow', 'raw'.
	at org.ovirt.engine.api.model.DiskFormat.fromValue(DiskFormat.java:40) [restapi-definition.jar:]
	at org.ovirt.engine.api.model.DiskFormat$Adapter.unmarshal(DiskFormat.java:46) [restapi-definition.jar:]
	at org.ovirt.engine.api.model.DiskFormat$Adapter.unmarshal(DiskFormat.java:43) [restapi-definition.jar:]
	at org.codehaus.jackson.xc.XmlAdapterJsonDeserializer.deserialize(XmlAdapterJsonDeserializer.java:61)
	... 110 more
```

**Comment by rgolangh** [comment]
I anticipated that empy disk format will cause that. The thing is I don't want to impose defaults here, because like you experienced, they need to match the underlying ovirt domain type.

So in order to solve this,  recreate the storage class, and add to the parameters section., where it states your ovirtStorageDomain,  `ovirtDiskFormat: "cow"`

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ovirt
provisioner: external/ovirt 
parameters:
  type: io1
  iopsPerGB: "10"
  ovirtStorageDomain: "iscsidomainname"
  fsType: ext4
  ovirtDiskFormat: "cow"
```

**Comment by righteousjester** [comment]
Thank you very much.
That has now created the PV

```
NAME                                       CAPACITY       ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM              STORAGECLASS   REASON    AGE
pvc-78f4f592-7ee7-11e8-8f21-001a4a1601ad   107374182400   RWO            Delete           Bound     default/registry   ovirt                    2m
```

However, I am receiving the following error when the pod tries to attach the storage

```
Events:
  Type     Reason                 Age                From                             Message
  ----     ------                 ----               ----                             -------
  Normal   Scheduled              46s                default-scheduler                Successfully assigned docker-registry-3-rnggh to nbschv093.xxxxxx
  Normal   SuccessfulMountVolume  46s                kubelet, nbschv093.xxxxxx
  MountVolume.SetUp succeeded for volume "registry-token-jlrqf"
  Normal   SuccessfulMountVolume  46s                kubelet, nbschv093.xxxxxx
  MountVolume.SetUp succeeded for volume "registry-certificates"
  Warning  FailedAttachVolume     12s (x7 over 46s)  attachdetach-controller          AttachVolume.Attach failed for volume "pvc-78f4f592-7ee7-11e8-8f21-001a4a1601ad" : invalid character 'j' looking for beginning of value
```

**Comment by rgolangh** [comment]
Did you pull ovirt-flexvolume-driver containers? this fix touches them as well. If not make the replication controller to refresh the containers.

If that doesn't help please open a new issue and also attach the journal logs of the node that is running the pod (where the flex driver is trying to attach the disk)

Note to self: Add a test pod in the in the CI container in #32
